#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
        ##
        FichaSAT:
            class: App\Entity\FichaSAT
            form:
                title: 'Nueva Ficha Tecnica'
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['Default', 'FichaSAT'] }
            edit:
                title:  'Edit customer'
        ##
        Clientes:
            class: App\Entity\Clientes
            form:
                title: 'Nuevo cliente'
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['Default', 'Clientes'] }
            edit:
                title:  'Edit customer'
    design:
        brand_color: 'grey'
        color_scheme: 'light'

    site_name: 'GeSAT'