vich_uploader:
    db_driver: orm
    
    mappings:
        ficha_imagenes:
            uri_prefix:         '/images/fichacte'
            upload_destination: '%kernel.project_dir%/public/images/fichacte'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
