# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Clientes:
            class: App\Entity\Clientes
            label: 'Ficha Clientes'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Información basica', icon: 'pencil' }
                    - { property: 'nombre', label: 'Nombre', icon: 'customer'}
                    - { property: 'apellidos', label: 'Apellidos'}
                    - { property: 'dni', label: 'DNI/NIE'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Información de contacto', icon: 'phone' }
                    - { property: 'movil', label: 'Teléfono Móvil'}
                    - { property: 'telefonoFijo', label: 'Teléfono Fijo'}
                    - { property: 'email', type: 'email', label: 'Correo Electrónico'}
                    - { type: 'group', css_class: 'col-sm', label: 'Dirección', icon: 'map' }
                    - { property: 'direccion', label: ''}

            list:
                sort: ['fechaRegistro', 'DESC']
                fields:
                    - { property: 'id', type: 'int'}
                    - { property: 'fichas' , label: 'Total SAT'}    
                    - { property: 'nombre', type: 'string'}
                    - { property: 'apellidos', type: 'string'}
                    - { property: 'dni', type: 'string', label: 'DNI'}
                    - { property: 'movil', type: 'tel'}
                    - { property: 'email', type: 'email', label: 'Correo Electrónico'}
                    - { property: 'fechaRegistro', format: 'd/m/Y H:i:s' }
            # show:
            #     title: '%%entity_label%% (#%%entity_id%%)'
            #     fields:
            #         # - { type: 'group', css_class: 'col-sm-6', label: 'Información basica', icon: 'pencil' }
            #         - { property: 'nombre', type: 'string'}
            #         - { property: 'apellidos', type: 'string'}
            #         - { property: 'dni', type: 'string', label: 'DNI'}
            #         - { property: 'movil', type: 'tel', label: 'Teléfono Móvil'}
            #         - { property: 'telefonoFijo', type: 'tel', label: 'Teléfono Fijo'}
            #         - { property: 'email', type: 'email', label: 'Correo Electrónico'}                    
            #         - { property: 'fechaRegistro', format: 'd/m/Y H:i:s' }                

                    

                