# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    transport:            smtp
    host:                 smtp.gmail.com
    encryption:           ssl
    auth_mode:            login
    #disable_delivery: true
