# This file sets the configuration of the main menu. If your backend is simple,
# you probably can leave the 'menu' option empty and rely on the default menu
# created by EasyAdmin.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    list:
        actions:
        ##ACTIONS DE LOS FORMULARIOS DISEÑO Y VISUALIZACIÓN
            - { name: 'show', icon: 'search', label: '', title: 'Revisar' }
            - { name: 'edit', icon: 'pencil', label: '', title: 'Editar' }
            - { name: 'delete', icon: 'trash', label: '', title: 'Delete' }
    design:
        menu:
          - entity: 'Clientes'
            icon: 'user-circle'
            children:
              - { label: 'Nuevo Cliente', icon: 'user-plus', url: '?action=new&entity=Clientes' }
              - { label: 'Listado de Clientes', icon: 'users', url: '?action=list&entity=Clientes' }
          - entity: 'FichaSat'
            icon: 'bug'
            children:
              - { label: 'Nueva Ficha', icon: 'user-plus', url: '?action=new&entity=FichaSat' }
              - { label: 'Listado de Fichas', icon: 'users', url: '?action=list&entity=FichaSat' }
          - entity: 'Revisiones'
            icon: 'heartbeat'
            children:
              - { label: 'Nueva Revisión', icon: 'user-plus', url: '?action=new&entity=Revisiones' }
              - { label: 'Listado de Revisiones', icon: 'users', url: '?action=list&entity=Revisiones' }

