# This file sets the configuration of the main menu. If your backend is simple,
# you probably can leave the 'menu' option empty and rely on the default menu
# created by EasyAdmin.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    list:
        actions:
        ##ACTIONS DE LOS FORMULARIOS DISEÑO Y VISUALIZACIÓN
            - { name: 'show', icon: 'search', label: '', title: 'Revisar' }
            - { name: 'edit', icon: 'pencil', label: '', title: 'Editar' }
            - { name: 'delete', icon: 'trash', label: '', title: 'Delete' }
    design:
        menu:
            #Entidad Clientes
          - label: 'Clientes'
            icon: 'user-circle'
            children:
              - { entity: 'Clientes', label: 'Nuevo Cliente', icon: 'user-plus', params: { action: 'new' } }
              - { entity: 'Clientes', label: 'Listado de Clientes', icon: 'users'}
          #Entidad FichaSAT 
          - label: 'SAT'   
            icon: 'bug'
            children:
              - { entity: 'FichaSat', label: 'Nueva Ficha', icon: 'code', params: { action: 'new' } }
              - { entity: 'FichaSat', label: 'Listado de Fichas', icon: 'codepen'}
          #Entidad Revisiones
          - label: 'Revisiones SAT'
            icon: 'eye'
            children:
              - { entity: 'Revisiones', label: 'Nueva Revisión', icon: 'comment', params: { action: 'new' } }
              - { entity: 'Revisiones', label: 'Listado de Reisiones', icon: 'comments' }
              # - { entity: 'EstadoAveria', label: 'Listado de Reisiones', icon: 'cog' }
          # Configuración
          - label: 'Configuración'
            icon: 'cog'
            children:
              - { entity: 'EstadoAveria', label: 'Nuevo Estado', icon: 'cogs', params: { action: 'new' } }     
              - { entity: 'EstadoAveria', label: 'Listado de Estados', icon: 'cogs' }
     

